In [1]:
import numpy as np
import pandas as pd

In [2]:
base_totales = pd.read_excel('Total_medios_perú.xlsx')
base_integr = pd.read_excel('Integración_medios_perú.xlsx')

In [11]:
base_final = pd.merge(right=base_totales, left=base_integr, how='right', left_on='Author', right_on='Author')
base_final.fillna(inplace=True, value= 0)
base_final['% Integración'] = round(base_final['Integración']/base_final['Total'],3)
base_final

             Author  Integración  Total  % Integración
0             atvpe          1.0     71          0.014
1      elpopular_pe          8.0     70          0.114
2           tromepe          4.0     63          0.063
3    larepublica_pe          3.0     54          0.056
4   elcomercio_peru          1.0     51          0.020
5         gestionpe          5.0     48          0.104
6         diarioojo          4.0     40          0.100
7    panamericanatv          2.0     36          0.056
8       rppnoticias          4.0     36          0.111
9      diariocorreo          2.0     34          0.059
10       larazon_pe          2.0     21          0.095
11      expresoperu          0.0     13          0.000
12   agencia_andina          1.0     12          0.083
13       ovacionweb          0.0     10          0.000
14  radionacionalfm          1.0     10          0.100
15   americatv_peru          0.0      9          0.000
16        elbuho_pe          1.0      9          0.111
17       extra_peru          0.0      8          0.000
18        limaaldia          0.0      8          0.000
19     tvcosmosperu          1.0      8          0.125
20      revistawapa          0.0      7          0.000
21    elbocononline          0.0      6          0.000
22        lalupa_pe          0.0      4          0.000
23      panoramaptv          0.0      3          0.000
24    prensachalaca          0.0      3          0.000
25       inforegion          1.0      1          1.000
26     sanmartinaqp          0.0      1          0.000

In [12]:
base_final.to_excel('base_final.xlsx')

# Medios por pico

In [12]:
base_mayo = pd.read_excel('Abril.xlsx')
base_abril = pd.read_excel('Mayo.xlsx')
base_final = pd.merge(right=base_abril, left=base_mayo, how='outer', left_on='Medio', right_on='Medio')
base_final

               Medio  Reach Abril  Reach Mayo
0    panamericana.pe        864.0         NaN
1           trome.pe       2811.0      4685.0
2        perurec.com          0.0         NaN
3      elcomercio.pe       2905.0         NaN
4     larepublica.pe       2452.0      4904.0
5       limaaldia.pe          0.0         NaN
6             ojo.pe        274.0       822.0
7        radiouno.pe         43.0         NaN
8             rpp.pe       1645.0      3290.0
9   americatv.com.pe          NaN      2170.0
10     apnoticias.pe          NaN         0.0
11           wapa.pe          NaN       256.0
12         depor.com          NaN      1523.0
13   diariocorreo.pe          NaN      1260.0
14       eltiempo.pe          NaN        51.0
15        gestion.pe          NaN       808.0
16         lahora.pe          NaN         0.0
17     lazona.com.pe          NaN        65.0

In [13]:
base_final.fillna(0, inplace=True)
base_final

               Medio  Reach Abril  Reach Mayo
0    panamericana.pe        864.0         0.0
1           trome.pe       2811.0      4685.0
2        perurec.com          0.0         0.0
3      elcomercio.pe       2905.0         0.0
4     larepublica.pe       2452.0      4904.0
5       limaaldia.pe          0.0         0.0
6             ojo.pe        274.0       822.0
7        radiouno.pe         43.0         0.0
8             rpp.pe       1645.0      3290.0
9   americatv.com.pe          0.0      2170.0
10     apnoticias.pe          0.0         0.0
11           wapa.pe          0.0       256.0
12         depor.com          0.0      1523.0
13   diariocorreo.pe          0.0      1260.0
14       eltiempo.pe          0.0        51.0
15        gestion.pe          0.0       808.0
16         lahora.pe          0.0         0.0
17     lazona.com.pe          0.0        65.0

In [14]:
base_final.sort_values(by = ['Reach Mayo'], ascending = False, inplace = True)
base_final

               Medio  Reach Abril  Reach Mayo
4     larepublica.pe       2452.0      4904.0
1           trome.pe       2811.0      4685.0
8             rpp.pe       1645.0      3290.0
9   americatv.com.pe          0.0      2170.0
12         depor.com          0.0      1523.0
13   diariocorreo.pe          0.0      1260.0
6             ojo.pe        274.0       822.0
15        gestion.pe          0.0       808.0
11           wapa.pe          0.0       256.0
17     lazona.com.pe          0.0        65.0
14       eltiempo.pe          0.0        51.0
10     apnoticias.pe          0.0         0.0
7        radiouno.pe         43.0         0.0
5       limaaldia.pe          0.0         0.0
3      elcomercio.pe       2905.0         0.0
2        perurec.com          0.0         0.0
16         lahora.pe          0.0         0.0
0    panamericana.pe        864.0         0.0

In [15]:
base_final.to_excel('Base_medios_Perú_picos.xlsx')