# Generaci√≥n de base para el mapa

In [2]:
import numpy as np
import pandas as pd

In [3]:
base_1 = pd.read_csv("mensajes_7_feb_16_feb.csv")
base_2 = pd.read_csv("mensajes_17_feb_28_feb.csv")
base_racismo = base_1.append(base_2)
base_racismo['Count'] = 1
base_racismo

,Network,Message URL,Profile,Date,Message,Type,Content Type,Followers,Engagements,Location,Gender,Age,Likes,Dislikes,Comments,Shares,Theme,Count
0,Twitter,https://twitter.com/Padawanmx/statuses/1494174...,Padawanmx,2/16/2022 11:57 pm,Como sabes que un twittero es un pendejo?\n\nU...,Message,Link,1836,1,"Cuernavaca, Morelos, Mexico",Men,NaN,1,0,0,0,NaN,1
1,Twitter,https://twitter.com/leo_poblete/statuses/14941...,leo_poblete,2/16/2022 11:43 pm,"Agradezco el apoyo de @FiscaliaCDMX, y del gob...",Message,Link,344,13,"Naucalpan de Juarez, M√©xico, Mexico",Men,NaN,9,0,1,3,NaN,1
2,Twitter,https://twitter.com/DiversidadCDMX/statuses/14...,DiversidadCDMX,2/16/2022 11:37 pm,#Ent√©rate La @FiscaliaCDMX vincul√≥ a proceso a...,Message,Text Only,6653,102,"Colonia del Valle, Mexico City, Mexico",NaN,NaN,67,0,1,34,NaN,1
3,Twitter,https://twitter.com/mavagomez_/statuses/149416...,mavagomez_,2/16/2022 11:35 pm,"Que rabia me da ver a gente racista, sexista, ...",Message,Text Only,21280,97,"Los Angeles, California, United States",Women,NaN,93,0,0,4,NaN,1
4,Twitter,https://twitter.com/mavagomez_/statuses/149416...,mavagomez_,2/16/2022 11:33 pm,"Fernandcc El racismo no es una opini√≥n, es ign...",Mention,Text Only,21280,3,"Los Angeles, California, United States",Women,NaN,2,0,1,0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,Twitter,https://twitter.com/josephmendez4/statuses/149...,josephmendez4,2/17/2022 12:49 am,Todo es clasismo ahora ü§£,Message,Text Only,370,2,Honduras,Men,NaN,1,0,1,0,NaN,1
949,Twitter,https://twitter.com/Rideonbeat/statuses/149418...,Rideonbeat,2/17/2022 12:46 am,"JotaKMaldonado1 De morro me gustaba, no hab√≠a ...",Mention,Text Only,1910,1,"San Francisco Acuautla, M√©xico, Mexico",NaN,NaN,1,0,0,0,NaN,1
950,Twitter,https://twitter.com/dandrestruction/statuses/1...,dandrestruction,2/17/2022 12:42 am,"Pobre de la gringa, solo dijo que le mamaba la...",Message,Link,67,1,"Ecatepec, M√©xico, Mexico",NaN,NaN,1,0,0,0,NaN,1
951,Twitter,https://twitter.com/narudordnajela/statuses/14...,narudordnajela,2/17/2022 12:25 am,SergioSarmiento @M_OlgaSCordero Miserable clas...,Mention,Text Only,659,0,"Las Delicias, Baja California, Mexico",NaN,NaN,0,0,0,0,NaN,1
952,Twitter,https://twitter.com/ren_candia/statuses/149417...,ren_candia,2/17/2022 12:11 am,A los PANIAGUADOS CLASISTAS!! https://t.co/7Px...,Message,Link,469,0,"Xalapa de Enriquez, Veracruz, Mexico",NaN,NaN,0,0,0,0,NaN,1

In [12]:
base_negativa = pd.read_csv("mensajes_negativos_7_feb_28_feb.csv")
base_negativa['Count_negativo'] = 1
base_negativa.rename({"Followers": "Followers_negativo",	"Engagements": "Engagements_negativo", "Age":"Age_negativo", "Likes":"Likes_negativos",	
                      "Dislikes":"Dislikes_negativo",	"Comments":"Comments_negativo",	"Shares":"Shares_negativo"}, inplace=True, axis=1)
base_negativa

,Network,Message URL,Profile,Date,Message,Type,Content Type,Followers_negativo,Engagements_negativo,Location,Gender,Age_negativo,Likes_negativos,Dislikes_negativo,Comments_negativo,Shares_negativo,Theme,Count_negativo
0,Twitter,https://twitter.com/elcacabonita/statuses/1498...,elcacabonita,2/28/2022 11:39 pm,"Sus comentarios bien racistas de los del bar ""...",Message,Text Only,1705,1,"Nacogdoches, Texas, United States",NaN,NaN,1,0,0,0,NaN,1
1,Twitter,https://twitter.com/AxelGar56163124/statuses/1...,AxelGar56163124,2/28/2022 11:23 pm,jose5anchez Ni que ir a dormir maldito racista...,Mention,Photo,394,2,Guatemala,NaN,NaN,1,0,1,0,NaN,1
2,Twitter,https://twitter.com/jvalenci777/statuses/14985...,jvalenci777,2/28/2022 11:16 pm,HoracioFranco @casa_lamm @_VicenteSerrano El m...,Mention,Text Only,3345,0,"Naucalpan de Juarez, M√©xico, Mexico",NaN,NaN,0,0,0,0,NaN,1
3,Twitter,https://twitter.com/Clau07Rocha/statuses/14985...,Clau07Rocha,2/28/2022 10:45 pm,bbcmundo Que triste üò¢ cu√°ndo dejar√°n de ver el...,Mention,Text Only,91,12,"Magdalena Contreras, Mexico City, Mexico",NaN,NaN,12,0,0,0,NaN,1
4,Twitter,https://twitter.com/Omttl83/statuses/149850127...,Omttl83,2/28/2022 10:31 pm,"Ten√≠a raz√≥n super Vlad, racistas, clasistas y ...",Message,Photo,20,0,"Ciudad Nezahualcoyotl, M√©xico, Mexico",NaN,NaN,0,0,0,0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,Twitter,https://twitter.com/raticio/statuses/149078884...,raticio,2/7/2022 3:45 pm,yandellcr Cuidado lo demandan por racismo,Mention,Text Only,2130,2,Costa Rica,NaN,NaN,2,0,0,0,NaN,1
822,Twitter,https://twitter.com/Andres_Vingback/statuses/1...,Andres_Vingback,2/7/2022 3:42 pm,baritonoluna @OficialFrenaaa @gilbertolozanog ...,Mention,Text Only,354,2,Mexico,Men,NaN,0,0,2,0,Backlash,1
823,Twitter,https://twitter.com/VilchisJuan1/statuses/1490...,VilchisJuan1,2/7/2022 3:07 pm,Faitelson_ESPN Mexicanos. De verdad no s√© Dan ...,Mention,Photo,41,3,"Santa Rosa Jauregui, Quer√©taro, Mexico",Men,NaN,3,0,0,0,NaN,1
824,Twitter,https://twitter.com/sirfelipon/statuses/149076...,sirfelipon,2/7/2022 2:19 pm,#FelizLunes #FelizInicioDeSemanaLaboral y en F...,Message,Video,234,1,"Mejicanos, San Salvador, El Salvador",Women,NaN,1,0,0,0,Sexodiversidad,1
825,Twitter,https://twitter.com/edavidmtzm/statuses/149076...,edavidmtzm,2/7/2022 2:13 pm,"igrecf no s√© que fue m√°s clasista, que me lo d...",Mention,Text Only,1027,3,"Miguel Hidalgo, Mexico City, Mexico",Men,NaN,3,0,0,0,NaN,1

In [13]:
base_agrupada = base_racismo.groupby('Location').sum()
base_agrupada['Splitted'] = base_agrupada.index.str.split(',')
base_agrupada.loc[:, 'Ciudad'] = base_agrupada.Splitted.map(lambda x: x[0])
try:
    base_agrupada.loc[:, 'Estado'] = base_agrupada.Splitted.str[1].str.strip()
    base_agrupada.loc[:, 'Pa√≠s'] = base_agrupada.Splitted.str[2].str.strip()
    base_agrupada.drop('Splitted', inplace=True, axis=1)
    base_agrupada_mexico_positiva = base_agrupada[base_agrupada['Pa√≠s'] == "Mexico"]
except:
    print("Do Nothing")
base_agrupada_mexico_positiva

,Followers,Engagements,Age,Likes,Dislikes,Comments,Shares,Count,Ciudad,Estado,Pa√≠s
Location,,,,,,,,,,,
"Acambaro, Guanajuato, Mexico",89,0,0.0,0,0,0,0,1,Acambaro,Guanajuato,Mexico
"Acapulco de Juarez, Guerrero, Mexico",35443,51,0.0,40,0,4,7,10,Acapulco de Juarez,Guerrero,Mexico
"Aguascalientes, Aguascalientes, Mexico",12567,9,0.0,6,0,3,0,14,Aguascalientes,Aguascalientes,Mexico
"Amozoc de Mota, Puebla, Mexico",193,0,0.0,0,0,0,0,1,Amozoc de Mota,Puebla,Mexico
"Apodaca, Nuevo Le√≥n, Mexico",5399,89,0.0,73,0,11,5,5,Apodaca,Nuevo Le√≥n,Mexico
...,...,...,...,...,...,...,...,...,...,...,...
"Xalapa de Enriquez, Veracruz, Mexico",1546,7,0.0,6,0,1,0,4,Xalapa de Enriquez,Veracruz,Mexico
"Xochimilco, Mexico City, Mexico",12941,17,0.0,13,0,1,3,5,Xochimilco,Mexico City,Mexico
"Zacatecas, Zacatecas, Mexico",2212,10,0.0,7,0,3,0,2,Zacatecas,Zacatecas,Mexico
"Zacatelco, Tlaxcala, Mexico",1,0,0.0,0,0,0,0,1,Zacatelco,Tlaxcala,Mexico
"Zapopan, Jalisco, Mexico",14362,4,0.0,2,0,2,0,2,Zapopan,Jalisco,Mexico

In [14]:
base_agrupada = base_negativa.groupby('Location').sum()
base_agrupada['Splitted'] = base_agrupada.index.str.split(',')
base_agrupada.loc[:, 'Ciudad'] = base_agrupada.Splitted.map(lambda x: x[0])
try:
    base_agrupada.loc[:, 'Estado'] = base_agrupada.Splitted.str[1].str.strip()
    base_agrupada.loc[:, 'Pa√≠s'] = base_agrupada.Splitted.str[2].str.strip()
    base_agrupada.drop('Splitted', inplace=True, axis=1)
    base_agrupada_mexico_negativa = base_agrupada[base_agrupada['Pa√≠s'] == "Mexico"]
except:
    print("Do Nothing")
base_agrupada_mexico_negativa

,Followers_negativo,Engagements_negativo,Age_negativo,Likes_negativos,Dislikes_negativo,Comments_negativo,Shares_negativo,Count_negativo,Ciudad,Estado,Pa√≠s
Location,,,,,,,,,,,
"Acambaro, Guanajuato, Mexico",89,0,0.0,0,0,0,0,1,Acambaro,Guanajuato,Mexico
"Acapulco de Juarez, Guerrero, Mexico",27297,44,0.0,36,0,4,4,7,Acapulco de Juarez,Guerrero,Mexico
"Aguascalientes, Aguascalientes, Mexico",1322,2,0.0,1,0,1,0,8,Aguascalientes,Aguascalientes,Mexico
"Amozoc de Mota, Puebla, Mexico",193,0,0.0,0,0,0,0,1,Amozoc de Mota,Puebla,Mexico
"Apodaca, Nuevo Le√≥n, Mexico",2967,82,0.0,69,0,9,4,3,Apodaca,Nuevo Le√≥n,Mexico
...,...,...,...,...,...,...,...,...,...,...,...
"Villahermosa, Tabasco, Mexico",7936,4,0.0,4,0,0,0,3,Villahermosa,Tabasco,Mexico
"Xalapa de Enriquez, Veracruz, Mexico",1070,6,0.0,5,0,1,0,2,Xalapa de Enriquez,Veracruz,Mexico
"Xochimilco, Mexico City, Mexico",129,2,0.0,1,0,0,1,3,Xochimilco,Mexico City,Mexico
"Zacatecas, Zacatecas, Mexico",2212,10,0.0,7,0,3,0,2,Zacatecas,Zacatecas,Mexico
"Zacatelco, Tlaxcala, Mexico",1,0,0.0,0,0,0,0,1,Zacatelco,Tlaxcala,Mexico

In [20]:
base_agrupada_estados_mexico_positiva = base_agrupada_mexico_positiva.groupby("Estado").sum()
base_agrupada_estados_mexico_negativa = base_agrupada_mexico_negativa.groupby("Estado").sum()
base_agrupada_estados_mexico = pd.merge(left=base_agrupada_estados_mexico_negativa, right=base_agrupada_estados_mexico_positiva, right_on=base_agrupada_estados_mexico_positiva.index , left_on=base_agrupada_estados_mexico_negativa.index, how='inner')
base_agrupada_estados_mexico

,key_0,Followers_negativo,Engagements_negativo,Age_negativo,Likes_negativos,Dislikes_negativo,Comments_negativo,Shares_negativo,Count_negativo,Followers,Engagements,Age,Likes,Dislikes,Comments,Shares,Count
0,Aguascalientes,1335,9,0.0,7,0,1,1,9,12580,16,0.0,12,0,3,1,15
1,Baja California,1496,2,0.0,1,0,1,0,5,10498,30,0.0,18,0,9,3,13
2,Chiapas,495,2,0.0,2,0,0,0,3,2626,6,0.0,5,0,0,1,6
3,Coahuila,6760,3,0.0,2,0,1,0,3,13848,3,0.0,2,0,1,0,5
4,Colima,6305,1,0.0,0,0,1,0,2,6908,6,0.0,4,0,2,0,5
5,Guanajuato,3434,1,0.0,1,0,0,0,10,90916,371,0.0,295,0,30,46,29
6,Guerrero,27297,44,0.0,36,0,4,4,7,40442,66,0.0,52,0,5,9,12
7,Hidalgo,759,5,0.0,2,0,2,1,4,1154,5,0.0,2,0,2,1,5
8,Jalisco,31736,177,0.0,152,0,17,8,43,88360,268,0.0,222,0,33,13,86
9,Mexico City,155154,1224,0.0,875,0,86,263,131,807072,3373,0.0,2520,0,254,599,257
10,Michoac√°n,1029,6,0.0,3,0,0,3,6,3609,24,0.0,15,0,0,9,12
11,Morelos,2928,9,0.0,7,0,2,0,18,9293,82,0.0,50,0,6,26,27
12,M√©xico,69417,137,0.0,100,0,11,26,60,165554,317,0.0,235,0,39,43,121
13,Nayarit,45,0,0.0,0,0,0,0,1,806,1,0.0,1,0,0,0,2
14,Nuevo Le√≥n,41759,198,0.0,155,0,28,15,43,386841,557,0.0,429,0,65,63,89
15,Oaxaca,30294,27,0.0,18,0,6,3,6,112401,190,0.0,165,0,13,12,12
16,Puebla,5775,20,0.0,16,0,2,2,8,41402,60,0.0,38,0,10,12,25
17,Quer√©taro,75936,39,0.0,28,0,5,6,19,152893,122,0.0,96,0,14,12,45
18,San Luis Potos√≠,124,1,0.0,1,0,0,0,1,35646,32,0.0,23,0,5,4,5
19,Sinaloa,5899,25,0.0,20,0,1,4,3,14815,96,0.0,86,0,6,4,10
20,Sonora,30025,45,0.0,35,0,9,1,19,56234,141,0.0,103,0,20,18,35
21,Tabasco,9336,30,0.0,21,0,1,8,4,34094,45,0.0,33,0,1,11,11
22,Tamaulipas,2,1,0.0,0,0,1,0,1,27974,11,0.0,6,0,3,2,6
23,Tlaxcala,876,3,0.0,2,0,1,0,4,1568,6,0.0,4,0,2,0,6
24,Veracruz,7187,23,0.0,19,0,1,3,11,10384,28,0.0,23,0,2,3,16
25,Yucat√°n,38470,28,0.0,20,0,5,3,7,443202,262,0.0,194,0,12,56,21
26,Zacatecas,2212,10,0.0,7,0,3,0,2,3939,12,0.0,8,0,4,0,3

In [21]:
from sklearn import preprocessing
normalized_arr = preprocessing.normalize(base_agrupada_estados_mexico['Engagements'].to_numpy().reshape(1,-1))
rounded_arr = lambda x: round(x,4)
vfunc = np.vectorize(rounded_arr)
vfunc(normalized_arr)

array([[4.600e-03, 8.600e-03, 1.700e-03, 9.000e-04, 1.700e-03, 1.064e-01,
        1.890e-02, 1.400e-03, 7.680e-02, 9.670e-01, 6.900e-03, 2.350e-02,
        9.090e-02, 3.000e-04, 1.597e-01, 5.450e-02, 1.720e-02, 3.500e-02,
        9.200e-03, 2.750e-02, 4.040e-02, 1.290e-02, 3.200e-03, 1.700e-03,
        8.000e-03, 7.510e-02, 3.400e-03]])

In [37]:
scaler = preprocessing.MinMaxScaler()
base_agrupada_estados_mexicos_counts = base_agrupada_estados_mexico[['key_0','Count', 'Count_negativo']]
base_agrupada_estados_mexicos_counts.rename({'key_0': 'Estado'}, axis=1, inplace=True)
base_agrupada_estados_mexicos_counts.set_index('Estado', inplace=True)
base_agrupada_estados_mexicos_counts['% Odio'] = base_agrupada_estados_mexicos_counts['Count_negativo']/base_agrupada_estados_mexicos_counts['Count']
base_agrupada_estados_mexicos_counts.to_csv("Base_estados_mexicanos_completa.csv")
base_agrupada_estados_mexicos_counts

C:\Users\JOSE\anaconda3\envs\nltkenv\lib\site-packages\pandas\core\frame.py:5034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
C:\Users\JOSE\AppData\Local\Temp/ipykernel_15868/1745844275.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_agrupada_estados_mexicos_counts['% Odio'] = base_agrupada_estados_mexicos_counts['Count_negativo']/base_agrupada_estados_mexicos_counts['Count']

                 Count  Count_negativo    % Odio
Estado
Aguascalientes      15               9  0.600000
Baja California     13               5  0.384615
Chiapas              6               3  0.500000
Coahuila             5               3  0.600000
Colima               5               2  0.400000
Guanajuato          29              10  0.344828
Guerrero            12               7  0.583333
Hidalgo              5               4  0.800000
Jalisco             86              43  0.500000
Mexico City        257             131  0.509728
Michoac√°n           12               6  0.500000
Morelos             27              18  0.666667
M√©xico             121              60  0.495868
Nayarit              2               1  0.500000
Nuevo Le√≥n          89              43  0.483146
Oaxaca              12               6  0.500000
Puebla              25               8  0.320000
Quer√©taro           45              19  0.422222
San Luis Potos√≠      5               1  0.200000
Sinaloa             10               3  0.300000
Sonora              35              19  0.542857
Tabasco             11               4  0.363636
Tamaulipas           6               1  0.166667
Tlaxcala             6               4  0.666667
Veracruz            16              11  0.687500
Yucat√°n             21               7  0.333333
Zacatecas            3               2  0.666667

In [35]:
names = base_agrupada_estados_mexicos_counts.columns
d = scaler.fit_transform(base_agrupada_estados_mexicos_counts)
scaled_df = pd.DataFrame(d, columns=names)
scaled_df['Estado'] = base_agrupada_estados_mexico.index
scaled_df.set_index('Estado', inplace=True)
scaled_df.head(8)

           Count  Count_negativo
Estado
0       0.050980        0.061538
1       0.043137        0.030769
2       0.015686        0.015385
3       0.011765        0.015385
4       0.011765        0.007692
5       0.105882        0.069231
6       0.039216        0.046154
7       0.011765        0.023077

In [14]:
fulled_df = pd.merge(left= scaled_df, right= base_agrupada_estados_mexico, left_on=scaled_df.index, right_on=base_agrupada_estados_mexico.index, how="inner")
fulled_df.rename({'key_0':'Estado', 'Followers_x':'Followers_n'
                 , 'Engagements_x':'Engagements_n', 'Count_x':'Count_n'
                 , 'Count_y':'Count', 'Followers_y':'Followers', 'Engagements_y':'Engagements'}, inplace=True, axis=1)
fulled_df.set_index('Estado', inplace=True)
fulled_df

,Followers_n,Engagements_n,Count_n,Followers,Engagements,Count
Estado,,,,,,
Aguascalientes,0.002583,0.002173,0.012195,2803,19,3
Baja California,0.038418,0.003317,0.103659,40499,29,18
Chiapas,0.043982,0.014871,0.085366,46352,130,15
Chihuahua,0.000000,0.000000,0.000000,86,0,1
Coahuila,0.045528,0.000000,0.042683,47978,0,8
Colima,0.001162,0.000000,0.006098,1308,0,2
Guanajuato,0.014991,0.380005,0.103659,15855,3322,18
Guerrero,0.009105,0.002974,0.030488,9664,26,6
Hidalgo,0.013893,0.004690,0.073171,14701,41,13
Jalisco,0.034750,0.084878,0.201220,36641,742,34
Mexico City,1.000000,1.000000,1.000000,1052018,8742,165
Michoac√°n,0.018497,0.017044,0.079268,19544,149,14
Morelos,0.024803,0.023450,0.109756,26177,205,19
M√©xico,0.049423,0.020018,0.365854,52076,175,61
Nayarit,0.000004,0.000000,0.006098,90,0,2
Nuevo Le√≥n,0.087665,0.049531,0.317073,92304,433,53
Oaxaca,0.026301,0.003432,0.030488,27753,30,6
Puebla,0.023301,0.014299,0.170732,24597,125,29
Quer√©taro,0.131637,0.003889,0.231707,138559,34,39
Quintana Roo,0.003905,0.002173,0.012195,4194,19,3
San Luis Potos√≠,0.001202,0.000000,0.018293,1350,0,4
Sinaloa,0.016479,0.004118,0.048780,17421,36,9
Sonora,0.016250,0.018760,0.103659,17180,164,18
Tabasco,0.001535,0.006863,0.018293,1701,60,4
Tamaulipas,0.025736,0.001830,0.036585,27159,16,7
Veracruz,0.008669,0.005605,0.121951,9205,49,21
Yucat√°n,0.154702,0.025967,0.103659,162822,227,18
Zacatecas,0.000009,0.000915,0.000000,95,8,1

In [15]:
scaled_df.to_excel("Base_estados_mexicanos_normalizada.xlsx")
scaled_df.to_csv("Base_estados_mexicanos_normalizada.csv")
fulled_df.to_csv("Base_estados_mexicanos_completa.csv")